---
title: "Seasonal Variations in Mortality Rates Among Shelter Residents in Toronto: Is Winter the Deadliest Season?"
author: 
  - Kevin Cai
thanks: "Code and data are available at: https://github.com/kevicai/toronto-sheltered-residents-deaths-analysis"
date: today
date-format: long
abstract: "This study explores Toronto winters' influence the morality rates among sheltered residents, utilizing data from 2007-2023. I explore on how cold weather impacts those in shelters by drawing upon previous research that highlights increased risks for homeless populations during colder months. I find that mortality rates in spring, summer, and fall are similar, while winter shows a slight increase compared to the other seasons. This finding suggests while homeless shelters do help to lower the risk of death in winter, further meaures should be taken to protect sheltered individuals against cold weather."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```

# Introduction

Homelessness is a persistent issue in Canada, with Toronto fostering to the largest population of homeless individuals in the country @homelessStats. On any given night, an estimated 10,000 people in Toronto are without a permanent home, with many relying on Toronto shelters for safety and warmth @homelessStats. Despite the city of Toronto providing shelters for these homeless people, sheltered residents still face many health risks. 

Previous research has shown that homeless populations are at an increased risk of mortality by cold temperatures, particularly during the winter months @winterAffets. This paper aims to explore seasonal variations in mortality rates among shelter residents in Toronto between 2007 and 2023. By comparing mortality rates across winter, spring, summer, and fall, I seek to determine whether winter poses a disproportionately high risk for sheltered individuals. 

The remainder of this paper is structured as follows: @sec-data addresses the data used in the analysis, @sec-results presents the results, @sec-discussion disscusses my findings and limitations in the results.

# Data {#sec-data}

# Results {#sec-results}

# Discussion {#sec-discussion}

# References


